version: '2'
services:
    prestigegateway-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/PrestigeGateway/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=PrestigeGateway
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
